export default {
  solid: [
    'faHome',
    'faCouch',
    'faHeart',
    'faBell',
    'faArrowLeft',
    'faThermometerHalf',
    'faTemperatureHigh',
    'faPlug',
    'faQuestion',
    'faEllipsisV',
    'faSlash',
    'faSync',
    'faPlay',
    'faPause',
    'faStop',
    'faSearchLocation',
    'faBatteryEmpty',
    'faBatteryQuarter',
    'faBatteryHalf',
    'faBatteryThreeQuarters',
    'faBatteryFull',
    'faTrash',
    'faStopwatch',
    'faHourglass',
    'faExclamationCircle',
    'faBolt',
    'faRoute'
  ],
  regular: ['faLightbulb', 'faEye'],
  light: [],
  duotone: [],
  brands: []
}
