query AllDevices {
  devices {
    uid
    name
    title
    description
    type
    class
    room
    available
    turn
    turnable
    state
  }
}

query DevicesByRoom($room: String) {
  devices(filter: {room: $room}) {
    uid
    name
    title
    description
    type
    class
    room
    available
    turn
    turnable
    lastUpdate
    state
    tags
    extraAttrs
  }
}

query DevicesByType($type: String) {
  devices(filter: {type: $type}) {
    uid
    name
    title
    description
    type
    class
    room
    available
    turn
    turnable
    lastUpdate
    state
    tags
    extraAttrs
  }
}

mutation Update ($uid: String!, $state: JSON!) {
  setState(deviceUid: $uid, newState: $state)
}

subscription WatchUpdates {
  deviceUpdated {
    uid
    available
    turn
    state
    lastUpdate
  }
}
